#!/usr/bin/env python
import subprocess
import ConfigParser

config = ConfigParser.ConfigParser()
config.read('acsoo.cfg')
version = config.get('acsoo', 'version')

# for the sudo commands below to work, the sudoers file must contain
# %odoo-test    ALL = (odoo-test) NOPASSWD: ALL
# and the user must be in the odoo-car-dev group on the target machine

subprocess.check_call([
    'rsync', '--verbose', '--recursive', '--times', '--delete',
    '--rsync-path', 'sudo -u odoo-prod rsync',
    'release/',
    'denis@192.168.178.100:/home/odoo-prod/instance/release/',
])
subprocess.check_call([
    'ssh', 'denis@192.168.178.100',
    'sudo -H -u odoo-prod /home/odoo-prod/instance/install.sh ' + version,
])
